/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ian' at '7/11/16 3:04 PM' with Gradle 2.14
 *
 * @author ian, @date 7/11/16 3:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
