import org.testng.annotations.*;
import static org.testng.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'ian' at '7/11/16 3:04 PM' with Gradle 2.14
 *
 * @author ian, @date 7/11/16 3:04 PM
 */
public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
